version: '3.8'

services:
  uniswap-db:
    image: postgres:13-alpine
    container_name: uniswap-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - uniswap-net

  uniswap-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniswap-app
    depends_on:
      - uniswap-db
    environment:
      DATABASE_HOST: uniswap-db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      UNISWAP_URL: ${UNISWAP_URL}
    ports:
      - '3030:3030'
    networks:
      - uniswap-net

networks:
  uniswap-net:
    driver: bridge

volumes:
  postgres_data:
